package completion

const (
	VAR         = "var"
	IF          = "if"
	ELSE        = "else"
	FOR         = "for"
	FUNC        = "func"
	GO          = "go"
	GOTO        = "goto"
	PACKAGE     = "package"
	BREAK       = "break"
	CONTINUE    = "continue"
	RANGE       = "range"
	CASE        = "case"
	DEFER       = "defer"
	RETURN      = "return"
	CHAN        = "chan"
	CONST       = "const"
	TYPE        = "type"
	SWITCH      = "switch"
	IMPORT      = "import"
	INTERFACE   = "interface"
	SELECT      = "select"
	DEFAULT     = "default"
	FALLTHROUGH = "fallthrough"
	STRUCT      = "struct"
	MAP         = "map"
)
